### PR TITLE
Updated mirrors

### PR DESCRIPTION
**Pull request by skmedix**
All the checksums should match.

PS. Instead of `tcetest_full_run_gz_url` we can probably use `tcetest049.zip` from merlin1991, but I will get to it later eventually

### CODE REVIEW

**Comment by skmedix** [comment]
@illwieckz Friendly ping :)

**Comment by illwieckz** [comment]
Thanks for the ping, I was not available when you posted the PR and then I forgot about it, I'll try to look at it this week-end. 🙂️

**Comment by illwieckz** [comment]
It works well! Thanks for the patch, it is now merged.

Also, I discovered that I had a similar patch unmerged on my local repository, but yours was more complete. 👍️

**Comment by illwieckz** [comment]
> we can probably use `tcetest049.zip` from merlin1991

Now done. 😉️

**Pull request merged**
